POST http://localhost:8080/auth/authenticate
Content-Type: application/json

{
  "email":"balakshin1357@yandex.ru",
  "password": "123"
}
###
GET http://localhost:8080/cultures/getTips/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYWxha3NoaW4xMzU3QHlhbmRleC5ydSIsImlhdCI6MTY4MDA4MzQzNiwiZXhwIjoxNjgwMDk0MjM2fQ.Vy4YTwRMxuqdBMVMKWhtno1RrCosLD8GMEM4_euxe80

###
GET http://localhost:8080/cultures/getOptimalTime/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJOQkBlbWFpbC5ydSIsImlhdCI6MTY3OTUwNTg1MiwiZXhwIjoxNjc5NTE2NjUyfQ.6kLpdkE-yLhoHkfO21Knb-BrqycEeT-sBDFikWG-koc

###
POST http://localhost:8080/weather/notifications/True
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYWxha3NoaW4xMzU3QHlhbmRleC5ydSIsImlhdCI6MTY4MDA4MzQzNiwiZXhwIjoxNjgwMDk0MjM2fQ.Vy4YTwRMxuqdBMVMKWhtno1RrCosLD8GMEM4_euxe80

###
GET http://localhost:8080/weather/alert/Оймякон
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYWxha3NoaW4xMzU3QHlhbmRleC5ydSIsImlhdCI6MTY4MDE1NzY4OSwiZXhwIjoxNjgwMTY4NDg5fQ.ORnOhddSklKarx5swWUaIuCCFmombPM0gpUmoMsKC4s

###
POST http://localhost:8080/sendMail
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYWxha3NoaW4xMzU3QHlhbmRleC5ydSIsImlhdCI6MTY4MDE1NzY4OSwiZXhwIjoxNjgwMTY4NDg5fQ.ORnOhddSklKarx5swWUaIuCCFmombPM0gpUmoMsKC4s
Content-Type: application/json

{
  "recipient":"Khayrullinbulka@gmail.com",
  "msgBody": "Здравствуйте, Булат! Команда Harvest Helper сердечно благодарит вас за доверие и надеется на плодотворное сотрудничество!",
  "subject": "Вы успешно зарегистрированы в Harvest Helper!"
}